package env

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/meop/ghpm/internal/config"
	"github.com/meop/ghpm/internal/store"
)

type DetectedShells struct {
	POSIX bool
	Nu    bool
	PWSh  bool
}

func DetectShells() DetectedShells {
	var s DetectedShells
	for _, name := range []string{"sh", "bash", "zsh"} {
		if _, err := exec.LookPath(name); err == nil {
			s.POSIX = true
			break
		}
	}
	if _, err := exec.LookPath("nu"); err == nil {
		s.Nu = true
	}
	if _, err := exec.LookPath("pwsh"); err == nil {
		s.PWSh = true
	}
	return s
}

func sortedKeys(manifest *config.Manifest) []string {
	keys := make([]string, 0, len(manifest.Extracts))
	for k := range manifest.Extracts {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// ContentFor returns the env script content for the given shell, suitable for
// direct eval (e.g. eval "$(ghpm env)") or writing to a file.
func ContentFor(shell string, manifest *config.Manifest) (string, error) {
	keys := sortedKeys(manifest)
	switch strings.ToLower(shell) {
	case "sh", "bash", "zsh", "dash", "posix":
		return shContent(keys, manifest), nil
	case "nu", "nushell":
		return nuContent(keys, manifest), nil
	case "pwsh", "powershell":
		return ps1Content(keys, manifest), nil
	default:
		return "", fmt.Errorf("unsupported shell: %s (supported: zsh, bash, pwsh, powershell, nu, nushell)", shell)
	}
}

func Generate(manifest *config.Manifest) ([]string, error) {
	shells := DetectShells()
	scriptsDir, err := store.ScriptsDir()
	if err != nil {
		return nil, err
	}

	keys := sortedKeys(manifest)
	var generated []string

	if shells.POSIX {
		path := filepath.Join(scriptsDir, "path.sh")
		if err := os.WriteFile(path, []byte(shContent(keys, manifest)), 0644); err != nil {
			return generated, fmt.Errorf("writing path.sh: %w", err)
		}
		generated = append(generated, path)
	} else {
		_ = os.Remove(filepath.Join(scriptsDir, "path.sh"))
	}

	if shells.Nu {
		path := filepath.Join(scriptsDir, "path.nu")
		if err := os.WriteFile(path, []byte(nuContent(keys, manifest)), 0644); err != nil {
			return generated, fmt.Errorf("writing path.nu: %w", err)
		}
		generated = append(generated, path)
	} else {
		_ = os.Remove(filepath.Join(scriptsDir, "path.nu"))
	}

	if shells.PWSh {
		path := filepath.Join(scriptsDir, "path.ps1")
		if err := os.WriteFile(path, []byte(ps1Content(keys, manifest)), 0644); err != nil {
			return generated, fmt.Errorf("writing path.ps1: %w", err)
		}
		generated = append(generated, path)
	} else {
		_ = os.Remove(filepath.Join(scriptsDir, "path.ps1"))
	}

	return generated, nil
}


func shContent(keys []string, manifest *config.Manifest) string {
	var b strings.Builder
	b.WriteString("# generated by ghpm — do not edit\n")

	for _, key := range keys {
		pkg := manifest.Extracts[key]
		if pkg.BinDir == "" {
			continue
		}
		writeShPath(&b, fmt.Sprintf("$HOME/.ghpm/extracts/%s/%s", key, pkg.BinDir))
	}

	return b.String()
}

// writeShPath emits a case block that prepends path to PATH only if not already present.
// path may contain shell variables like $HOME which are expanded at eval time.
func writeShPath(b *strings.Builder, path string) {
	fmt.Fprintf(b, "case \":$PATH:\" in\n")
	fmt.Fprintf(b, "  *\":%s:\"*) ;;\n", path)
	fmt.Fprintf(b, "  *) export PATH=\"%s${PATH:+:$PATH}\" ;;\n", path)
	fmt.Fprintf(b, "esac\n")
}

func nuContent(keys []string, manifest *config.Manifest) string {
	var b strings.Builder
	b.WriteString("# generated by ghpm — do not edit\n")

	for _, key := range keys {
		pkg := manifest.Extracts[key]
		if pkg.BinDir == "" {
			continue
		}
		writeNuPath(&b, fmt.Sprintf(`$env.HOME + "/.ghpm/extracts/%s/%s"`, key, pkg.BinDir))
	}

	return b.String()
}

func writeNuPath(b *strings.Builder, pathExpr string) {
	fmt.Fprintf(b, "$env.PATH = (\n  $env.PATH\n  | where $it != (%s)\n  | prepend (%s)\n)\n", pathExpr, pathExpr)
}

func ps1Content(keys []string, manifest *config.Manifest) string {
	var b strings.Builder
	b.WriteString("# generated by ghpm — do not edit\n")

	for _, key := range keys {
		pkg := manifest.Extracts[key]
		if pkg.BinDir == "" {
			continue
		}
		writePS1Path(&b, fmt.Sprintf("$env:HOME%[1]s.ghpm%[1]sextracts%[1]s%s%[1]s%s",
			string(filepath.Separator), key, filepath.FromSlash(pkg.BinDir)))
	}

	return b.String()
}

func writePS1Path(b *strings.Builder, path string) {
	fmt.Fprintf(b, "if (-not ($env:PATH -split [IO.Path]::PathSeparator -contains \"%s\")) {\n", path)
	fmt.Fprintf(b, "  $env:PATH = \"%s\" + [IO.Path]::PathSeparator + $env:PATH\n", path)
	b.WriteString("}\n")
}
