package entrypoint

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/meop/ghpm/internal/config"
	"github.com/meop/ghpm/internal/store"
)

type DetectedShells struct {
	POSIX bool
	Nu    bool
	PWSh  bool
}

func DetectShells() DetectedShells {
	var s DetectedShells
	for _, name := range []string{"sh", "bash", "zsh"} {
		if _, err := exec.LookPath(name); err == nil {
			s.POSIX = true
			break
		}
	}
	if _, err := exec.LookPath("nu"); err == nil {
		s.Nu = true
	}
	if _, err := exec.LookPath("pwsh"); err == nil {
		s.PWSh = true
	}
	return s
}

func Generate(manifest *config.Manifest) ([]string, error) {
	shells := DetectShells()
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}
	scriptsDir, err := store.ScriptsDir()
	if err != nil {
		return nil, err
	}

	keys := make([]string, 0, len(manifest.Installs))
	for k := range manifest.Installs {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var generated []string

	if shells.POSIX {
		path := filepath.Join(scriptsDir, "env.sh")
		if err := writeSh(path, home, keys, manifest); err != nil {
			return generated, fmt.Errorf("writing env.sh: %w", err)
		}
		generated = append(generated, path)
	} else {
		_ = os.Remove(filepath.Join(scriptsDir, "env.sh"))
	}

	if shells.Nu {
		path := filepath.Join(scriptsDir, "env.nu")
		if err := writeNu(path, home, keys, manifest); err != nil {
			return generated, fmt.Errorf("writing env.nu: %w", err)
		}
		generated = append(generated, path)
	} else {
		_ = os.Remove(filepath.Join(scriptsDir, "env.nu"))
	}

	if shells.PWSh {
		path := filepath.Join(scriptsDir, "env.ps1")
		if err := writePS1(path, home, keys, manifest); err != nil {
			return generated, fmt.Errorf("writing env.ps1: %w", err)
		}
		generated = append(generated, path)
	} else {
		_ = os.Remove(filepath.Join(scriptsDir, "env.ps1"))
	}

	return generated, nil
}

func GenerateFor(shell string, manifest *config.Manifest) ([]string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}
	scriptsDir, err := store.ScriptsDir()
	if err != nil {
		return nil, err
	}

	keys := make([]string, 0, len(manifest.Installs))
	for k := range manifest.Installs {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	switch strings.ToLower(shell) {
	case "sh", "bash", "zsh":
		path := filepath.Join(scriptsDir, "env.sh")
		return []string{path}, writeSh(path, home, keys, manifest)
	case "nu", "nushell":
		path := filepath.Join(scriptsDir, "env.nu")
		return []string{path}, writeNu(path, home, keys, manifest)
	case "pwsh", "powershell":
		path := filepath.Join(scriptsDir, "env.ps1")
		return []string{path}, writePS1(path, home, keys, manifest)
	default:
		return nil, fmt.Errorf("unsupported shell: %s (supported: sh, nu, pwsh)", shell)
	}
}

func writeSh(path, home string, keys []string, manifest *config.Manifest) error {
	var b strings.Builder
	b.WriteString("# generated by ghpm — do not edit\n")
	fmt.Fprintf(&b, "GHPM=\"%s/.ghpm\"\n", home)
	b.WriteString("export PATH=\"$GHPM/bin:$GHPM/packages")

	for _, key := range keys {
		pkg := manifest.Installs[key]
		if pkg.Paths == nil {
			continue
		}
		for _, p := range pkg.Paths["bin"] {
			fmt.Fprintf(&b, "/%s/%s", key, p)
		}
	}
	b.WriteString("${PATH:+:$PATH}\"\n")

	for _, key := range keys {
		pkg := manifest.Installs[key]
		if pkg.Paths == nil {
			continue
		}
		if len(pkg.Paths["lib"]) > 0 || len(pkg.Paths["man"]) > 0 || len(pkg.Paths["share"]) > 0 {
			fmt.Fprintf(&b, "\n# %s\n", key)
		}
		for _, p := range pkg.Paths["lib"] {
			fmt.Fprintf(&b, "export LD_LIBRARY_PATH=\"$GHPM/packages/%s/%s${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"\n", key, p)
		}
		for _, p := range pkg.Paths["man"] {
			fmt.Fprintf(&b, "export MANPATH=\"$GHPM/packages/%s/%s${MANPATH:+:$MANPATH}\"\n", key, p)
		}
		sharePaths := pkg.Paths["share"]
		manPaths := pkg.Paths["man"]
		if len(sharePaths) > 0 && len(manPaths) == 0 {
			for _, p := range sharePaths {
				fmt.Fprintf(&b, "export XDG_DATA_DIRS=\"$GHPM/packages/%s/%s${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}\"\n", key, p)
			}
		}
	}

	b.WriteString("\nunset GHPM\n")
	return os.WriteFile(path, []byte(b.String()), 0644)
}

func writeNu(path, home string, keys []string, manifest *config.Manifest) error {
	var b strings.Builder
	b.WriteString("# generated by ghpm — do not edit\n")
	fmt.Fprintf(&b, "let ghpm = \"%s/.ghpm\"\n\n", home)

	b.WriteString("$env.PATH = ($env.PATH | prepend $\"($ghpm)/bin\"")
	for _, key := range keys {
		pkg := manifest.Installs[key]
		if pkg.Paths == nil {
			continue
		}
		for _, p := range pkg.Paths["bin"] {
			fmt.Fprintf(&b, " | prepend $\"($ghpm)/packages/%s/%s\"", key, p)
		}
	}
	b.WriteString(")\n")

	if runtime.GOOS == "linux" {
		for _, key := range keys {
			pkg := manifest.Installs[key]
			if pkg.Paths == nil {
				continue
			}
			for _, p := range pkg.Paths["lib"] {
				fmt.Fprintf(&b, "$env.LD_LIBRARY_PATH = ($env.LD_LIBRARY_PATH | default \"\" | prepend $\"($ghpm)/packages/%s/%s\")\n", key, p)
			}
			for _, p := range pkg.Paths["man"] {
				fmt.Fprintf(&b, "$env.MANPATH = ($env.MANPATH | default \"\" | prepend $\"($ghpm)/packages/%s/%s\")\n", key, p)
			}
		}
	}

	return os.WriteFile(path, []byte(b.String()), 0644)
}

func writePS1(path, home string, keys []string, manifest *config.Manifest) error {
	var b strings.Builder
	b.WriteString("# generated by ghpm — do not edit\n")
	homePS := home
	fmt.Fprintf(&b, "$ghpm = \"%s\\.ghpm\"\n", homePS)

	b.WriteString("\n$env:PATH = \"$ghpm\\bin")
	for _, key := range keys {
		pkg := manifest.Installs[key]
		if pkg.Paths == nil {
			continue
		}
		for _, p := range pkg.Paths["bin"] {
			fmt.Fprintf(&b, ";$ghpm\\packages\\%s\\%s", key, filepath.FromSlash(p))
		}
	}
	b.WriteString(";$env:PATH\"\n")

	if runtime.GOOS == "linux" {
		for _, key := range keys {
			pkg := manifest.Installs[key]
			if pkg.Paths == nil {
				continue
			}
			for _, p := range pkg.Paths["lib"] {
				fmt.Fprintf(&b, "$env:LD_LIBRARY_PATH = \"$ghpm/packages/%s/%s${env:LD_LIBRARY_PATH:+:$env:LD_LIBRARY_PATH}\"\n", key, p)
			}
			for _, p := range pkg.Paths["man"] {
				fmt.Fprintf(&b, "$env:MANPATH = \"$ghpm/packages/%s/%s${env:MANPATH:+:$env:MANPATH}\"\n", key, p)
			}
		}
	}

	return os.WriteFile(path, []byte(b.String()), 0644)
}
