package entrypoint

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/meop/ghpm/internal/config"
)

type DetectedShells struct {
	POSIX bool
	Nu    bool
	PWSh  bool
}

func DetectShells() DetectedShells {
	var s DetectedShells
	for _, name := range []string{"sh", "bash", "zsh"} {
		if _, err := exec.LookPath(name); err == nil {
			s.POSIX = true
			break
		}
	}
	if _, err := exec.LookPath("nu"); err == nil {
		s.Nu = true
	}
	if _, err := exec.LookPath("pwsh"); err == nil {
		s.PWSh = true
	}
	return s
}

func Generate(manifest *config.Manifest) ([]string, error) {
	shells := DetectShells()
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}
	base := filepath.Join(home, ".ghpm")

	keys := make([]string, 0, len(manifest.Installs))
	for k := range manifest.Installs {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var generated []string

	if shells.POSIX {
		path := filepath.Join(base, "entrypoint.sh")
		if err := writeSh(path, home, keys, manifest); err != nil {
			return generated, fmt.Errorf("writing entrypoint.sh: %w", err)
		}
		generated = append(generated, path)
	} else {
		_ = os.Remove(filepath.Join(base, "entrypoint.sh"))
	}

	if shells.Nu {
		path := filepath.Join(base, "entrypoint.nu")
		if err := writeNu(path, home, keys, manifest); err != nil {
			return generated, fmt.Errorf("writing entrypoint.nu: %w", err)
		}
		generated = append(generated, path)
	} else {
		_ = os.Remove(filepath.Join(base, "entrypoint.nu"))
	}

	if shells.PWSh {
		path := filepath.Join(base, "entrypoint.ps1")
		if err := writePS1(path, home, keys, manifest); err != nil {
			return generated, fmt.Errorf("writing entrypoint.ps1: %w", err)
		}
		generated = append(generated, path)
	} else {
		_ = os.Remove(filepath.Join(base, "entrypoint.ps1"))
	}

	return generated, nil
}

func GenerateFor(shell string, manifest *config.Manifest) ([]string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}
	base := filepath.Join(home, ".ghpm")

	keys := make([]string, 0, len(manifest.Installs))
	for k := range manifest.Installs {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	switch strings.ToLower(shell) {
	case "sh", "bash", "zsh":
		path := filepath.Join(base, "entrypoint.sh")
		return []string{path}, writeSh(path, home, keys, manifest)
	case "nu", "nushell":
		path := filepath.Join(base, "entrypoint.nu")
		return []string{path}, writeNu(path, home, keys, manifest)
	case "pwsh", "powershell":
		path := filepath.Join(base, "entrypoint.ps1")
		return []string{path}, writePS1(path, home, keys, manifest)
	default:
		return nil, fmt.Errorf("unsupported shell: %s (supported: sh, nu, pwsh)", shell)
	}
}

func writeSh(path, home string, keys []string, manifest *config.Manifest) error {
	var b strings.Builder
	b.WriteString("# generated by ghpm — do not edit\n")
	fmt.Fprintf(&b, "GHPM_PKGS=\"%s/.ghpm/packages\"\n", home)

	for _, key := range keys {
		pkg := manifest.Installs[key]
		if pkg.Paths == nil {
			continue
		}
		fmt.Fprintf(&b, "\n# %s\n", key)
		for _, p := range pkg.Paths["bin"] {
			fmt.Fprintf(&b, "export PATH=\"$GHPM_PKGS/%s/%s${PATH:+:$PATH}\"\n", key, p)
		}
		for _, p := range pkg.Paths["lib"] {
			fmt.Fprintf(&b, "export LD_LIBRARY_PATH=\"$GHPM_PKGS/%s/%s${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"\n", key, p)
		}
		for _, p := range pkg.Paths["man"] {
			fmt.Fprintf(&b, "export MANPATH=\"$GHPM_PKGS/%s/%s${MANPATH:+:$MANPATH}\"\n", key, p)
		}
		sharePaths := pkg.Paths["share"]
		manPaths := pkg.Paths["man"]
		if len(sharePaths) > 0 && len(manPaths) == 0 {
			for _, p := range sharePaths {
				fmt.Fprintf(&b, "export XDG_DATA_DIRS=\"$GHPM_PKGS/%s/%s${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}\"\n", key, p)
			}
		}
	}

	b.WriteString("\nunset GHPM_PKGS\n")
	return os.WriteFile(path, []byte(b.String()), 0644)
}

func writeNu(path, home string, keys []string, manifest *config.Manifest) error {
	var b strings.Builder
	b.WriteString("# generated by ghpm — do not edit\n")
	fmt.Fprintf(&b, "let ghpm_pkgs = \"%s/.ghpm/packages\"\n\n", home)

	for _, key := range keys {
		pkg := manifest.Installs[key]
		if pkg.Paths == nil {
			continue
		}
		fmt.Fprintf(&b, "# %s\n", key)
		for _, p := range pkg.Paths["bin"] {
			fmt.Fprintf(&b, "$env.PATH = ($env.PATH | prepend $\"($ghpm_pkgs)/%s/%s\")\n", key, p)
		}
	}

	return os.WriteFile(path, []byte(b.String()), 0644)
}

func writePS1(path, home string, keys []string, manifest *config.Manifest) error {
	var b strings.Builder
	b.WriteString("# generated by ghpm — do not edit\n")
	fmt.Fprintf(&b, "$ghpm = \"%s\\.ghpm\\packages\"\n", ps1Home(home))

	for _, key := range keys {
		pkg := manifest.Installs[key]
		if pkg.Paths == nil {
			continue
		}
		fmt.Fprintf(&b, "\n# %s\n", key)
		for _, p := range pkg.Paths["bin"] {
			fmt.Fprintf(&b, "$env:PATH = \"$ghpm\\%s\\%s;$env:PATH\"\n", key, filepath.FromSlash(p))
		}
	}

	return os.WriteFile(path, []byte(b.String()), 0644)
}

func ps1Home(home string) string {
	if runtime.GOOS == "windows" {
		return home
	}
	return home
}
